import cloud from '@lafjs/cloud'
const db = cloud.mongo.db

// 初始化菜单、角色数据
export default async function (ctx: FunctionContext) {
  // 强制初始化数据 如果为 true 会清空原来的数据库重新添加
  const force = true

  initData.forEach(async (item) => {
    const dbName = item.dbName

    if (force) {
      try {
        const res = await db.dropCollection(dbName)
        console.log(dbName, res)
      } catch (e) {
        console.log('Collection does not exist')
      }
    }
    const data = item.data
    await addDataToCollectionIfNotExists(dbName, data)
  })
  return
}

async function addDataToCollectionIfNotExists(dbName, data) {
  try {
    const collectionNames = await db.listCollections().toArray()
    const collectionExists = collectionNames.some(
      (collection) => collection.name === dbName
    )

    if (!collectionExists) {
      await db.createCollection(dbName)
      const collection = db.collection(dbName)
      await collection.insertMany(data)
      console.log(`数据成功添加到集合 ${dbName}`)
    } else {
      console.log(`集合 ${dbName} 已存在，数据未添加`)
    }
  } catch (error) {
    console.error(error)
  }
}

const initData = [
  {
    // 菜单管理表数据
    dbName: 'menu_manage',
    data: [
      {
        _id: '1001',
        parent_id: '',
        type: 1,
        name: 'dashboard',
        path: '/dashboard',
        component: 'Layout',
        redirect: '',
        icon: 'fa fa-laptop',
        permission: '',
        title: '控制台',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 0,
        create_time: 1697390346000,
        update_time: 1697390346000,
      },
      {
        _id: '1002',
        parent_id: '1001',
        type: 2,
        name: 'console',
        path: '/dashboard/console',
        component: '/console/index',
        redirect: '',
        icon: 'fa fa-laptop',
        permission: '',
        title: '控制台',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: true,
        remark: '',
        status: 1,
        sort: 0,
        create_time: 1697390346001,
        update_time: 1697390346001,
      },
      {
        _id: '1003',
        parent_id: '',
        type: 1,
        name: 'system',
        path: '/system',
        component: 'Layout',
        redirect: '',
        icon: 'fa fa-gears',
        permission: '',
        title: '系统管理',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 1,
        create_time: 1697390346003,
        update_time: 1697390346003,
      },
      {
        _id: '1004',
        parent_id: '1003',
        type: 2,
        name: 'sysUser',
        path: '/system/user',
        component: '/system/user/index',
        redirect: '',
        icon: 'fa fa-user',
        permission: '',
        title: '用户管理',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 0,
        create_time: 1697390346004,
        update_time: 1697390346004,
      },
      {
        _id: '1005',
        parent_id: '1004',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/user/auth/getUserList',
        title: '查询',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 0,
        create_time: 1697390346005,
        update_time: 1697390346005,
      },
      {
        _id: '1006',
        parent_id: '1004',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/user/auth/addUser',
        title: '新增',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 1,
        create_time: 1697390346006,
        update_time: 1697390346006,
      },
      {
        _id: '1007',
        parent_id: '1004',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/user/auth/updateUser',
        title: '编辑',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 2,
        create_time: 1697390346007,
        update_time: 1697390346007,
      },
      {
        _id: '1008',
        parent_id: '1004',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/user/auth/deleteUser',
        title: '删除',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 3,
        create_time: 1697390346008,
        update_time: 1697390346008,
      },
      {
        _id: '1009',
        parent_id: '1003',
        type: 2,
        name: 'sysMenu',
        path: '/system/menu',
        component: '/system/menu/index',
        redirect: '',
        icon: 'fa fa-list-ul',
        permission: '',
        title: '菜单管理',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 1,
        create_time: 1697390346009,
        update_time: 1697390346009,
      },
      {
        _id: '1010',
        parent_id: '1009',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/menu/auth/getMenuList',
        title: '查询',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 0,
        create_time: 1697390346010,
        update_time: 1697390346010,
      },
      {
        _id: '1011',
        parent_id: '1009',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/menu/auth/addMenu',
        title: '新增',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 1,
        create_time: 1697390346011,
        update_time: 1697390346011,
      },
      {
        _id: '1012',
        parent_id: '1009',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/menu/auth/updateMenu',
        title: '编辑',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 2,
        create_time: 1697390346012,
        update_time: 1697390346012,
      },
      {
        _id: '1013',
        parent_id: '1009',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/menu/auth/deleteMenu',
        title: '删除',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 3,
        create_time: 1697390346013,
        update_time: 1697390346013,
      },
      {
        _id: '1014',
        parent_id: '1003',
        type: 2,
        name: 'sysRole',
        path: '/system/role',
        component: '/system/role/index',
        redirect: '',
        icon: 'fa fa-sitemap',
        permission: '',
        title: '角色管理',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 2,
        create_time: 1697390346014,
        update_time: 1697390346014,
      },
      {
        _id: '1015',
        parent_id: '1014',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/role/auth/getRoleList',
        title: '查询',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 0,
        create_time: 1697390346015,
        update_time: 1697390346015,
      },
      {
        _id: '1016',
        parent_id: '1014',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/role/auth/addRole',
        title: '新增',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 1,
        create_time: 1697390346016,
        update_time: 1697390346016,
      },
      {
        _id: '1017',
        parent_id: '1014',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/role/auth/updateRole',
        title: '编辑',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 2,
        create_time: 1697390346017,
        update_time: 1697390346017,
      },
      {
        _id: '1018',
        parent_id: '1014',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/role/auth/deleteRole',
        title: '删除',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 4,
        create_time: 1697390346018,
        update_time: 1697390346018,
      },
      {
        _id: '1019',
        parent_id: '1003',
        type: 2,
        name: 'sysRecharge',
        path: '/system/recharge',
        component: '/system/recharge/index',
        redirect: '',
        icon: 'fa fa-leanpub',
        permission: '',
        title: '充值模板',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 3,
        create_time: 1697390346019,
        update_time: 1697390346019,
      },
      {
        _id: '1020',
        parent_id: '1019',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/recharge/auth/getRechargeTemplateList',
        title: '查询',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 0,
        create_time: 1697390346020,
        update_time: 1697390346020,
      },
      {
        _id: '1021',
        parent_id: '1019',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/recharge/auth/addRechargeTemplate',
        title: '新增',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 1,
        create_time: 1697390346021,
        update_time: 1697390346021,
      },
      {
        _id: '1022',
        parent_id: '1019',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/recharge/auth/updateRechargeTemplate',
        title: '编辑',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 2,
        create_time: 1697390346022,
        update_time: 1697390346022,
      },
      {
        _id: '1023',
        parent_id: '1019',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/recharge/auth/deleteRechargeTemplate',
        title: '删除',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 3,
        create_time: 1697390346023,
        update_time: 1697390346023,
      },
      {
        _id: '1024',
        parent_id: '1003',
        type: 2,
        name: 'sysCdkey',
        path: '/system/cdkey',
        component: '/system/cdkey/index',
        redirect: '',
        icon: 'fa fa-credit-card',
        permission: '',
        title: '卡密管理',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 4,
        create_time: 1697390346024,
        update_time: 1697390346024,
      },
      {
        _id: '1025',
        parent_id: '1024',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/cdkey/auth/getCdkeyList',
        title: '查询',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 0,
        create_time: 1697390346025,
        update_time: 1697390346025,
      },
      {
        _id: '1026',
        parent_id: '1024',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/cdkey/auth/addCdkey',
        title: '新增',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 1,
        create_time: 1697390346026,
        update_time: 1697390346026,
      },
      {
        _id: '1027',
        parent_id: '1024',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/cdkey/auth/updateCdkey',
        title: '编辑',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 2,
        create_time: 1697390346027,
        update_time: 1697390346027,
      },
      {
        _id: '1028',
        parent_id: '1024',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/cdkey/auth/deleteCdkey',
        title: '删除',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 3,
        create_time: 1697390346028,
        update_time: 1697390346028,
      },
      {
        _id: '1029',
        parent_id: '1003',
        type: 2,
        name: 'sysPayConfig',
        path: '/system/pay_config',
        component: '/system/pay_config/index',
        redirect: '',
        icon: 'fa fa-wrench',
        permission: '',
        title: '支付配置',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 5,
        create_time: 1697390346029,
        update_time: 1697390346029,
      },
      {
        _id: '1030',
        parent_id: '1029',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/pay_config/auth/getPayConfigList',
        title: '查询',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 0,
        create_time: 1697390346030,
        update_time: 1697390346030,
      },
      {
        _id: '1031',
        parent_id: '1029',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/pay_config/auth/addPayConfig',
        title: '新增',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 1,
        create_time: 1697390346031,
        update_time: 1697390346031,
      },
      {
        _id: '1032',
        parent_id: '1029',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/pay_config/auth/updatePayConfig',
        title: '编辑',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 2,
        create_time: 1697390346032,
        update_time: 1697390346032,
      },
      {
        _id: '1033',
        parent_id: '1029',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/pay_config/auth/deletePayConfig',
        title: '删除',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 3,
        create_time: 1697390346033,
        update_time: 1697390346033,
      },
      {
        _id: '1034',
        parent_id: '1003',
        type: 2,
        name: 'sysParameter',
        path: '/system/parameter',
        component: '/system/parameter/index',
        redirect: '',
        icon: 'fa fa-sliders',
        permission: '',
        title: '系统参数',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 6,
        create_time: 1697390346034,
        update_time: 1697390346034,
      },
      {
        _id: '1035',
        parent_id: '1034',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/parameter/auth/getParameterList',
        title: '查询',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 0,
        create_time: 1697390346035,
        update_time: 1697390346035,
      },
      {
        _id: '1036',
        parent_id: '1034',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/parameter/auth/addParameter',
        title: '新增',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 1,
        create_time: 1697390346036,
        update_time: 1697390346036,
      },
      {
        _id: '1037',
        parent_id: '1034',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/parameter/auth/updateParameter',
        title: '编辑',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 2,
        create_time: 1697390346037,
        update_time: 1697390346037,
      },
      {
        _id: '1038',
        parent_id: '1034',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/parameter/auth/deleteParameter',
        title: '删除',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 3,
        create_time: 1697390346038,
        update_time: 1697390346038,
      },
      {
        _id: '1039',
        parent_id: '',
        type: 1,
        name: 'content',
        path: '/content',
        component: 'Layout',
        redirect: '',
        icon: 'fa fa-newspaper-o',
        permission: '',
        title: '内容管理',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 3,
        create_time: 1697390346039,
        update_time: 1697390346039,
      },
      {
        _id: '1040',
        parent_id: '1039',
        type: 2,
        name: 'contentArticleCategory',
        path: '/content/article_category',
        component: '/content/article_category/index',
        redirect: '',
        icon: 'fa fa-th-large',
        permission: '',
        title: '文章分类',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 0,
        create_time: 1697390346040,
        update_time: 1697390346040,
      },
      {
        _id: '1041',
        parent_id: '1040',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission:
          'service/content/article_category/auth/getArticleCategoryList',
        title: '查询',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 0,
        create_time: 1697390346041,
        update_time: 1697390346041,
      },
      {
        _id: '1042',
        parent_id: '1040',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/content/article_category/auth/addArticleCategory',
        title: '新增',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 1,
        create_time: 1697390346042,
        update_time: 1697390346042,
      },
      {
        _id: '1043',
        parent_id: '1040',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission:
          'service/content/article_category/auth/updateArticleCategory',
        title: '编辑',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 2,
        create_time: 1697390346043,
        update_time: 1697390346043,
      },
      {
        _id: '1044',
        parent_id: '1040',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission:
          'service/content/article_category/auth/deleteArticleCategory',
        title: '删除',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 3,
        create_time: 1697390346044,
        update_time: 1697390346044,
      },
      {
        _id: '1045',
        parent_id: '1039',
        type: 2,
        name: 'contentArticle',
        path: '/content/article',
        component: '/content/article/index',
        redirect: '',
        icon: 'fa fa-list-alt',
        permission: '',
        title: '文章管理',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 1,
        create_time: 1697390346045,
        update_time: 1697390346045,
      },
      {
        _id: '1046',
        parent_id: '1045',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/content/article/auth/getArticleList',
        title: '查询',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 0,
        create_time: 1697390346046,
        update_time: 1697390346046,
      },
      {
        _id: '1047',
        parent_id: '1045',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/content/article/auth/addArticle',
        title: '新增',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 1,
        create_time: 1697390346047,
        update_time: 1697390346047,
      },
      {
        _id: '1048',
        parent_id: '1045',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/content/article/auth/updateArticle',
        title: '编辑',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 2,
        create_time: 1697390346048,
        update_time: 1697390346048,
      },
      {
        _id: '1049',
        parent_id: '1045',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/content/article/auth/deleteArticle',
        title: '删除',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 3,
        create_time: 1697390346049,
        update_time: 1697390346049,
      },
      {
        _id: '1050',
        parent_id: '',
        type: 1,
        name: 'business',
        path: '/business',
        component: 'Layout',
        redirect: '',
        icon: 'fa fa-folder-open',
        permission: '',
        title: '业务管理',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 3,
        create_time: 1697390346050,
        update_time: 1697390346050,
      },
      {
        _id: '1051',
        parent_id: '1050',
        type: 2,
        name: 'businessAccount',
        path: '/business/account',
        component: '/business/account/index',
        redirect: '',
        icon: 'fa fa-user-circle-o',
        permission: '',
        title: '用户中心',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 1,
        create_time: 1697390346051,
        update_time: 1697390346051,
      },
      {
        _id: '1052',
        parent_id: '1050',
        type: 2,
        name: 'businessRechargeRecord',
        path: '/business/recharge_record',
        component: '/business/recharge_record/index',
        redirect: '',
        icon: 'fa fa-list-alt',
        permission: '',
        title: '充值记录',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 2,
        create_time: 1697390346052,
        update_time: 1697390346052,
      },
      {
        _id: '1053',
        parent_id: '',
        type: 1,
        name: 'maintenance',
        path: '/maintenance',
        component: 'Layout',
        redirect: '',
        icon: 'fa fa-shield',
        permission: '',
        title: '运维管理',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 3,
        create_time: 1697390346053,
        update_time: 1697390346053,
      },
      {
        _id: '1054',
        parent_id: '1053',
        type: 2,
        name: 'businessOperateLog',
        path: '/maintenance/operate_log',
        component: '/maintenance/operate_log/index',
        redirect: '',
        icon: 'fa fa-database',
        permission: '',
        title: '操作日志',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 2,
        create_time: 1697390346052,
        update_time: 1697390346052,
      },
      {
        _id: '1055',
        parent_id: '1053',
        type: 2,
        name: 'businessSystemLog',
        path: '/maintenance/system_log',
        component: '/maintenance/system_log/index',
        redirect: '',
        icon: 'fa fa-bitbucket',
        permission: '',
        title: '系统日志',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 2,
        create_time: 1697390346055,
        update_time: 1697390346055,
      },
      {
        _id: '65f6c9bd99c368cdcb812ca4',
        parent_id: '1003',
        type: 2,
        name: 'messageManager',
        path: '/system/message',
        component: '/system/message/index',
        redirect: '',
        icon: 'fa fa-comment',
        permission: '',
        title: '推送管理',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 0,
        create_time: 1710672317735,
        update_time: 1710672317735,
      },
      {
        _id: '65f6cdcc99c368cdcb812d9a',
        parent_id: '65f6c9bd99c368cdcb812ca4',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/message/auth/getList',
        title: '查询',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: false,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 0,
        create_time: 1710673356784,
        update_time: 1710673356784,
      },
      {
        _id: '65f6ce2599c368cdcb812dca',
        parent_id: '65f6c9bd99c368cdcb812ca4',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/message/auth/add',
        title: '新增推送',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: false,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 0,
        create_time: 1710673445370,
        update_time: 1710673445370,
      },
    ],
  },
  {
    // 角色管理表数据
    dbName: 'role_manage',
    data: [
      {
        _id: '1001',
        code: 'admin',
        name: '管理员角色',
        description: '拥有管理员的权限',
        menu_auth: [
          '1001',
          '1002',
          '1003',
          '1004',
          '1005',
          '1006',
          '1007',
          '1008',
          '1009',
          '1010',
          '1011',
          '1012',
          '1013',
          '1014',
          '1015',
          '1016',
          '1017',
          '1018',
          '1019',
          '1020',
          '1021',
          '1022',
          '1023',
          '1024',
          '1025',
          '1026',
          '1027',
          '1028',
          '1029',
          '1030',
          '1031',
          '1032',
          '1033',
          '1034',
          '1035',
          '1036',
          '1037',
          '1038',
          '1039',
          '1040',
          '1041',
          '1042',
          '1043',
          '1044',
          '1045',
          '1046',
          '1047',
          '1048',
          '1049',
          '1050',
          '1051',
          '1052',
          '1053',
          '1054',
          '1055',
          '65f6c9bd99c368cdcb812ca4',
          '65f6cdcc99c368cdcb812d9a',
          '65f6ce2599c368cdcb812dca',
        ],
        status: 1,
        create_time: 1697459240000,
        update_time: 1697459240000,
      },
      {
        _id: '1002',
        code: 'common',
        name: '普通用户角色',
        description: '只是普通用户级的权限',
        menu_auth: ['1001', '1002'],
        status: 1,
        create_time: 1697459271000,
        update_time: 1697459271000,
      },
      {
        _id: '1003',
        code: 'demo',
        name: '演示用户角色',
        description: '只是演示用户级的权限',
        menu_auth: [
          '1001',
          '1002',
          '1003',
          '1004',
          '1005',
          '1006',
          '1007',
          '1008',
          '1009',
          '1010',
          '1011',
          '1012',
          '1013',
          '1014',
          '1015',
          '1016',
          '1017',
          '1018',
          '1019',
          '1020',
          '1021',
          '1022',
          '1023',
          '1024',
          '1025',
          '1026',
          '1027',
          '1028',
          '1029',
          '1030',
          '1031',
          '1032',
          '1033',
          '1034',
          '1035',
          '1036',
          '1037',
          '1038',
          '1039',
          '1040',
          '1041',
          '1042',
          '1043',
          '1044',
          '1045',
          '1046',
          '1047',
          '1048',
          '1049',
          '1050',
          '1051',
          '1052',
          '1053',
          '1054',
          '1055',
        ],
        status: 1,
        create_time: 1697459271000,
        update_time: 1697459271000,
      },
    ],
  },
]
