import cloud from '@lafjs/cloud'
const db = cloud.mongo.db

// 初始化菜单、角色数据
export default async function (ctx: FunctionContext) {
  // 强制初始化数据 如果为 true 会清空原来的数据库重新添加
  const force = true

  initData.forEach(async (item) => {
    const dbName = item.dbName

    if (force) {
      try {
        const res = await db.dropCollection(dbName)
        console.log(dbName, res)
      } catch (e) {
        console.log('Collection does not exist')
      }
    }
    const data = item.data
    await addDataToCollectionIfNotExists(dbName, data)
  })
  return
}

async function addDataToCollectionIfNotExists(dbName, data) {
  try {
    const collectionNames = await db.listCollections().toArray()
    const collectionExists = collectionNames.some(
      (collection) => collection.name === dbName
    )

    if (!collectionExists) {
      await db.createCollection(dbName)
      const collection = db.collection(dbName)
      await collection.insertMany(data)
      console.log(`数据成功添加到集合 ${dbName}`)
    } else {
      console.log(`集合 ${dbName} 已存在，数据未添加`)
    }
  } catch (error) {
    console.error(error)
  }
}

const initData = [
  {
    // 菜单管理表数据
    dbName: 'menu_manage',
    data: [
      {
        _id: '1001',
        parent_id: '',
        type: 1,
        name: 'dashboard',
        path: '/dashboard',
        component: 'Layout',
        redirect: '',
        icon: 'fa fa-laptop',
        permission: '',
        title: '控制台',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 0,
        create_time: 1697390346000,
        update_time: 1697390346000
      },
      {
        _id: '1002',
        parent_id: '1001',
        type: 2,
        name: 'console',
        path: '/dashboard/console',
        component: '/console/index',
        redirect: '',
        icon: 'fa fa-laptop',
        permission: '',
        title: '控制台',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: true,
        remark: '',
        status: 1,
        sort: 0,
        create_time: 1697390346001,
        update_time: 1697390346001
      },
      {
        _id: '1003',
        parent_id: '',
        type: 1,
        name: 'system',
        path: '/system',
        component: 'Layout',
        redirect: '',
        icon: 'fa fa-gears',
        permission: '',
        title: '系统管理',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 1,
        create_time: 1697390346003,
        update_time: 1697390346003
      },
      {
        _id: '1004',
        parent_id: '1003',
        type: 2,
        name: 'sysUser',
        path: '/system/user',
        component: '/system/user/index',
        redirect: '',
        icon: 'fa fa-user',
        permission: '',
        title: '用户管理',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 0,
        create_time: 1697390346004,
        update_time: 1697390346004
      },
      {
        _id: '1005',
        parent_id: '1004',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/user/sys/getUserList',
        title: '查询',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 0,
        create_time: 1697390346005,
        update_time: 1697390346005
      },
      {
        _id: '1006',
        parent_id: '1004',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/user/sys/addUser',
        title: '新增',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 1,
        create_time: 1697390346006,
        update_time: 1697390346006
      },
      {
        _id: '1007',
        parent_id: '1004',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/user/sys/updateUser',
        title: '编辑',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 2,
        create_time: 1697390346007,
        update_time: 1697390346007
      },
      {
        _id: '1008',
        parent_id: '1004',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/user/sys/deleteUser',
        title: '删除',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 3,
        create_time: 1697390346008,
        update_time: 1697390346008
      },
      {
        _id: '1009',
        parent_id: '1003',
        type: 2,
        name: 'sysMenu',
        path: '/system/menu',
        component: '/system/menu/index',
        redirect: '',
        icon: 'fa fa-list-ul',
        permission: '',
        title: '菜单管理',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 1,
        create_time: 1697390346009,
        update_time: 1697390346009
      },
      {
        _id: '1010',
        parent_id: '1009',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/menu/sys/getMenuList',
        title: '查询',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 0,
        create_time: 1697390346010,
        update_time: 1697390346010
      },
      {
        _id: '1011',
        parent_id: '1009',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/menu/sys/addMenu',
        title: '新增',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 1,
        create_time: 1697390346011,
        update_time: 1697390346011
      },
      {
        _id: '1012',
        parent_id: '1009',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/menu/sys/updateMenu',
        title: '编辑',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 2,
        create_time: 1697390346012,
        update_time: 1697390346012
      },
      {
        _id: '1013',
        parent_id: '1009',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/menu/sys/deleteMenu',
        title: '删除',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 3,
        create_time: 1697390346013,
        update_time: 1697390346013
      },
      {
        _id: '1014',
        parent_id: '1003',
        type: 2,
        name: 'sysRole',
        path: '/system/role',
        component: '/system/role/index',
        redirect: '',
        icon: 'fa fa-sitemap',
        permission: '',
        title: '角色管理',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 2,
        create_time: 1697390346014,
        update_time: 1697390346014
      },
      {
        _id: '1015',
        parent_id: '1014',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/role/sys/getRoleList',
        title: '查询',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 0,
        create_time: 1697390346015,
        update_time: 1697390346015
      },
      {
        _id: '1016',
        parent_id: '1014',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/role/sys/addRole',
        title: '新增',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 1,
        create_time: 1697390346016,
        update_time: 1697390346016
      },
      {
        _id: '1017',
        parent_id: '1014',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/role/sys/updateRole',
        title: '编辑',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 2,
        create_time: 1697390346017,
        update_time: 1697390346017
      },
      {
        _id: '1018',
        parent_id: '1014',
        type: 3,
        name: '',
        path: '',
        component: '',
        redirect: '',
        icon: '',
        permission: 'service/role/sys/deleteRole',
        title: '删除',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 4,
        create_time: 1697390346018,
        update_time: 1697390346018
      },
      {
        _id: '1019',
        parent_id: '',
        type: 1,
        name: 'business',
        path: '/business',
        component: 'Layout',
        redirect: '',
        icon: 'fa fa-folder-open',
        permission: '',
        title: '业务管理',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 3,
        create_time: 1697390346019,
        update_time: 1697390346019
      },
      {
        _id: '1020',
        parent_id: '1019',
        type: 2,
        name: 'businessAccount',
        path: '/business/account',
        component: '/business/account/index',
        redirect: '',
        icon: 'fa fa-user-circle-o',
        permission: '',
        title: '用户中心',
        is_frame: false,
        out_link: '',
        is_hide: false,
        is_keep_alive: true,
        is_affix: false,
        remark: '',
        status: 1,
        sort: 1,
        create_time: 1697390346020,
        update_time: 1697390346020
      }
    ]
  },
  {
    // 角色管理表数据
    dbName: 'role_manage',
    data: [
      {
        _id: '1001',
        code: 'admin',
        name: '管理员',
        description: '拥有管理员的权限',
        menu_auth: [
          '1001',
          '1002',
          '1003',
          '1004',
          '1005',
          '1006',
          '1007',
          '1008',
          '1009',
          '1010',
          '1011',
          '1012',
          '1013',
          '1014',
          '1015',
          '1016',
          '1017',
          '1018',
          '1019',
          '1020'
        ],
        status: 1,
        create_time: 1697459240000,
        update_time: 1697459240000
      },
      {
        _id: '1002',
        code: 'common',
        name: '普通用户',
        description: '只是普通用户级的权限',
        menu_auth: ['1001', '1002'],
        status: 1,
        create_time: 1697459271000,
        update_time: 1697459271000
      }
    ]
  }
]
