export { default as BasicTable } from './src/Table.vue'
export { default as BasicTableCustom } from './src/TableCustom.vue'
export { default as TableAction } from './src/components/TableAction.vue'
export * from './src/types/table'
export * from './src/types/tableAction'
