name: Hysli Admin Template Front Build Docker Image 

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  WEB_PATH: admin/
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.12.0'
      
      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install
        working-directory: ${{ env.WEB_PATH }}
      
      - name: PNPM Build
        run: pnpm run build
        working-directory: ${{ env.WEB_PATH }}
      
      - name: 构建并推送到 Dockerhub 镜像仓库
        uses: docker/build-push-action@v2
        with:
          context: .
          file: admin/Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/hysli-admin-template